[package]
name = "screenshot"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
objc-foundation = "0.1.1"
objc_id = "0.1.1"
image = "0.24.3"
egui = "0.19.0"
eframe = { version = "0.19.0", features = ["persistence"] }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
cc = "1.0.17"

[profile.dev.package."*"]
# Set the default for dependencies in Development mode.
opt-level = 3
